### ISSUE TITLE
No such file or directory: 'ANNOTATION_PATH'

### ISSUE THREAD

**Issue by fighting-j** [UMass-Foundation-Model/3D-VLA#4]
Hello, when I configure the environment according to the instructions and run bash launcher/train_ldm.sh, the following error appears：
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/3D-VLA/train_ldm_goal_image.py", line 950, in <module>
[rank0]:     main()
[rank0]:   File "/home/ubuntu/3D-VLA/train_ldm_goal_image.py", line 563, in main
[rank0]:     dataset = GoalDataset(args.ann_path, args.include_depth)
[rank0]:   File "/home/ubuntu/3D-VLA/lavis/datasets/datasets/goal_ldm_datasets.py", line 24, in __init__
[rank0]:     ann = json.load(open(json_path))
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: 'ANNOTATION_PATH'
I can't find the file that shows the error，How can I solve it.

**Comment by Kimho666** [comment]
Yes, I also has this problem. I dont know.

**Comment by Emokable** [comment]
I faced the same problem

**Comment by Vincentlu1412** [comment]
same problem!!
